### ISSUE TITLE
Old apache syntax causing 500 errors

### ISSUE THREAD

**Issue by mattbell87** [2pisoftware/cmfive-core#13]
On Apache 2.4x there are 500 errors when using cmfive-core.

Here is the code in [/.htaccess](https://github.com/2pisoftware/cmfive-core/blob/master/system/.htaccess) that's causing the problem

```apache
<Files ~ "\.php$">
    Order allow,deny
    Deny from all
</Files>
```

If this is changed to the newer syntax there are no longer 500 errors:

```apache
<Files ~ "\.php$">
    Require all denied
</Files>
```

**Comment by adam-buckley** [comment]
AFAIK it should be using both, as only having the ```Require all denied``` directive will in theory break on Apache <2.4. i.e:

```php
<Files ~ "\.php$">
    Order allow,deny
    Deny from all
    Require all denied
</Files>

**Comment by adam-buckley** [comment]
Actually, rereading that doesn't make a lot of sense to me, as I have the current configuration working fine on Apache 2.4. That rule is designed to stop anyone from accessing php files in cmfive-core directly. Please make sure your install of Cmfive follows the [Installation step](https://github.com/2pisoftware/cmfive-core) on the main page of this repo.

**Comment by mattbell87** [comment]
Apache docs seem to say the old stuff needs to be deleted. But yeah it will break on older Apache as you say. https://httpd.apache.org/docs/2.4/upgrading.html

The 500 happens on all the JS and CSS files when installing.
