### ISSUE TITLE
Clearing Session files from ./storage

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive-core#170]
Hi @adam-buckley ,

I noticed in my private project that session files were not cleaned up in ./storage/session/ and were accumulating fast. I had to set up a cron job to clean them out daily with the following command:

`find /var/www/html/cmfive-boilerplate/storage/session/ -atime +7  -exec rm {} +;`

Is this an issue on all our prod servers?

**Comment by DerekCrannaford** [comment]
CDK deployments have session cleanup by CRON set up in user data.
I think older production servers have it in place already, from legacy/manual setup.

**Comment by adam-buckley** [comment]
Hi @careck. As Derek mentioned all of our deployments automatically set up a cron to cleanup the session files, our solution is more or less the same except we pipe into xargs to call rm instead of using exec in find.
