### ISSUE TITLE
Deprecated function call on Report module's "Create Report" page

### ISSUE THREAD

**Issue by dragonflyfree** [2pisoftware/cmfive-core#201]
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/cmfive-core/system/modules/report/actions/edit.php on line 64

**Comment by chris-bateman** [comment]
@dragonflyfree so this has a closed PR that was approved. https://github.com/2pisoftware/cmfive-core/pull/204

Were these changes pushed into another branch somewhere or can they be merged in?
