### ISSUE TITLE
Undefined variable warnings on Task module's "Activity" action

### ISSUE THREAD

**Issue by dragonflyfree** [2pisoftware/cmfive-core#202]
Warning: Undefined variable $members in /var/www/cmfive-core/system/modules/task/actions/taskweek.php on line 81
...
Warning: Undefined variable $group in /var/www/cmfive-core/system/modules/task/actions/taskweek.php on line 84

**Comment by chris-bateman** [comment]
@dragonflyfree similar for this one.  Approved but closed PR https://github.com/2pisoftware/cmfive-core/pull/203

**Comment by adam-buckley** [comment]
Closing as it seems to be fixed in PR. @dragonflyfree please reopen if that's not the case
