### ISSUE TITLE
Last login not updating properly

### ISSUE THREAD

**Issue by adam-buckley** [2pisoftware/cmfive-core#206]
I've noticed in a client deployment that the last login is not being set properly, it appears to be only set once.

**Comment by DerekCrannaford** [comment]
Notes:

- auth_module::user db_object class has a $dt_lastlogin
- and a method ->updateLastLogin()
- any auth sequences should call that method somewhere, but it seems not to be happening reliably
- setting up locally/codespaces and tracing authService->login() function is likely a good place to start
- bigger picture is to confirm it also works where auth is signed of by 'hooks' (alternate validation code)
