### ISSUE TITLE
User group membership cannot handle different accounts with the same name

### ISSUE THREAD

**Issue by adam-buckley** [2pisoftware/cmfive-core#207]
I'm not sure how we haven't seen this yet but if two different people have the same name, we will only ever see one of them in the user group membership list.

**Comment by chris-bateman** [comment]
@tynanmatthews @adam-buckley this PR was approved but has conflicts and possible failing tests.  Could it be merged with a quick review?
https://github.com/2pisoftware/cmfive-core/pull/218

**Comment by tynanmatthews** [comment]
Yeah this can definitely be merged, this was my first issue and I just forgot

**Comment by careck** [comment]
hi guys, pls don't forget about this
