### ISSUE TITLE
admin/users bugs

### ISSUE THREAD

**Issue by Dane-2pi** [2pisoftware/cmfive-core#208]
- Seems to be no template, present on develop and main. 

- Can't add new user. 

looks like a bootstrap 5 issue. Will revisit using derek's codespace setup

**Comment by rlockerbie** [comment]
This section is using a new layout that needs to be built, in the folder system/templates/base `run npm i && npm run prod`.

**Comment by adam-buckley** [comment]
@Dane-2pi can this be closed?
