### ISSUE TITLE
Security/Axios 0.18.0

### ISSUE THREAD

**Issue by DaltJM** [2pisoftware/cmfive-core#209]
https://security.snyk.io/vuln/SNYK-JS-AXIOS-1579269
https://security.snyk.io/vuln/SNYK-JS-AXIOS-1038255
https://security.snyk.io/vuln/SNYK-JS-AXIOS-174505

**Comment by DerekCrannaford** [comment]
@adam-buckley 

I gather this comes in per Foundation templates only, like:
registerComponent('axios', new CmfiveScriptComponent('/system/templates/js/axios.min.js')); 

Which indeed shows as v18x where the advisories state >v21

Bootstrap5 templating is already avoiding it?

**Comment by chris-bateman** [comment]
Can be closed - https://github.com/2pisoftware/cmfive-core/security/dependabot/54
