### ISSUE TITLE
Attachment model function updateAttachment throws an error

### ISSUE THREAD

**Issue by rlockerbie** [2pisoftware/cmfive-core#210]
Gaufrette is complaining about an incorrect file system type, FlySystem something. Maybe this function is deprecated? I've just switched to deleting the existing attachment and adding a new one.

**Comment by adam-buckley** [comment]
Hi Rob, Gaufrette has been removed in lieu of FlySystem for modern PHP support.Can you add more details on how to replicate the issue, the error message shown, etc.
