### ISSUE TITLE
Response code is 200 on fatal error?

### ISSUE THREAD

**Issue by mattbell87** [2pisoftware/cmfive-core#256]
I just noticed that a 200 is returned when there's a fatal error.

![image](https://github.com/2pisoftware/cmfive-core/assets/2722612/8b8e7aa0-cf31-4ea5-9736-a5697d6209a1)

This could affect health checks in the future. For example if cmfive is upgraded on kubernetes and it reports healthy the update will be deployed even if there are fatal errors.

**Comment by adam-buckley** [comment]
My guess is an nginx config issue?

**Comment by adam-buckley** [comment]
[I think so](https://stackoverflow.com/questions/52375375/php-fpm-always-returns-200-regardless-of-nginx-status-code)

**Comment by mattbell87** [comment]
Fixed in https://github.com/2pisoftware/cmfive-boilerplate/pull/115
