### ISSUE TITLE
Need to upgrade unit tests for PHPUnit v10

### ISSUE THREAD

**Issue by DerekCrannaford** [2pisoftware/cmfive-core#268]
upgrade unit tests for ver10, by adding [module]_ prefix to correctly resolve testable classes
(will need same refactor on any custom modules shipping their own unit tests)

![image](https://github.com/2pisoftware/cmfive-core/assets/43056286/f2d0f238-71ea-4728-852a-43fa5eea7594)

![image](https://github.com/2pisoftware/cmfive-core/assets/43056286/f0fed2e7-0b1b-4312-b7c5-367fa80cdacd)

**Comment by mattbell87** [comment]
Upgraded in https://github.com/2pisoftware/cmfive-core/pull/278
