### ISSUE TITLE
Task links in "My Timelog" report are broken.

### ISSUE THREAD

**Issue by kauer2** [2pisoftware/cmfive-core#283]
In the CRM "My TimeLog" report, in both the "Task Summary" and the "Detailed Time Log" sections, the links to the tasks are missing a slash between the domain name and the path. The links cannot be followed without manually adjusting them.

For example, if the link _should_ be `https://crm.2pisoftware.com/task/edit/13160`, it will be in the UI as `https://crm.2pisoftware.comtask/edit/13160`. Note that there is no forward slash between `com` and `task` in the latter URL. This makes the domain into `crm.2pisoftware.comtask` and the domain lookup fails if someone clicks the link.

The workaround is to wait for the lookup failure (which is more or less immediate), then manually add the slash at the right point in the location bar and press ENTER.

I found this when I requested a report on my time log entries between and including 22/1/2024 and 28/1/2024, with no task group and no time type specified. However, I would expect that anyone getting a report on any date interval, with or without task group or time type, would see the same problem provided there was at least one selected time log entry in the interval.

I reported this issue on 12/12/2023 last year in Mattermost:

https://chat.internal.2pisoftware.com/developers/pl/9exuujm18f8zidcnx6kamk8y4a

**Comment by careck** [comment]
this was due to $webroot having the trailing slash removed when the CRM was moved. This is now fixed.
