### ISSUE TITLE
Date Picker not working on Insights

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive-core#284]
Date fields on insight filter forms are not showing a date picker, which makes it impossible to enter a correct date.

![image](https://github.com/2pisoftware/cmfive-core/assets/487856/3dc5eee8-8d6e-4188-8c08-83e916ae939e)

This may have come as a consequence of removing jQuery?

**Comment by careck** [comment]
Hello has this been fixed?

**Comment by tynanmatthews** [comment]
yes in PR #101 waiting for a review before it can be merged
