### ISSUE TITLE
Login with wrong user name causes weird message

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive-core#285]
see this error message when I've tried to log in with a wrong username:

![image](https://github.com/2pisoftware/cmfive-core/assets/487856/23aae1e7-c0aa-4189-a88e-961cf1432f9e)

**Comment by tynanmatthews** [comment]
<img width="647" alt="Screenshot 2024-04-02 at 4 42 53 PM" src="https://github.com/2pisoftware/cmfive-core/assets/30655787/9bd76f75-8878-46aa-895c-3259b65f2728">

I'm unable to replicate this issue, perhaps it is to do with a config file or is a browser related issue?
