### ISSUE TITLE
New Design Search does not work and looks bad

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive-core#288]
1. please extend the input field
2. when clicking the search button, nothing happens other than the modal closing

![image](https://github.com/2pisoftware/cmfive-core/assets/487856/d356af09-a492-49ac-af6e-4cee4c7823f5)

**Comment by MaddyUnderStars** [comment]
@careck I've found the issue, but I'd like to know how best to fix it. As far as I know, the intent behind the existing code is to always have a <label> along with a <input>, which isn't the case here. I could add one, but that would mean changing the design more. I could change the CSS to not require this instead, but that breaks the intent.
